service: serverless-todos

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs4.3

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /hello
          method: get
